auto: true
server: true
pygments: true
markdown: maruku

# site url
#url: cooleyweb.com

# custom vars
name: Syntax Optional
full-name: Brett Cooley
email: brett@cooleyweb.org

# exclude files for generated site
exclude: 
- README.md
