auto: true
server: true
pygments: true
markdown: maruku
permalink: /posts/:year/:month/:day/:title

# custom vars
name: Syntax Optional
full-name: Brett Cooley
email: brett@cooleyweb.org
phone: +13036018090
phone_read: 303 601 8090
self: https://github.com/brcooley/brcooley.github.com

# exclude files for generated site
exclude:
- README.md
