auto: true
server: true
pygments: true
markdown: maruku
permalink: /posts/:year/:month/:day/:title

# custom vars
name: Syntax Optional
full-name: Brett Cooley
email: brett@cooleyweb.org

# exclude files for generated site
exclude:
- README.md
